version: '3.8'

services:
  frontend:
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - "80:80" # Map port 80 on the host to port 80 in the container
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    restart: always
